from typing import Protocol, List
from .contracts import SnapshotManifest, OpResult

# Giao diện cho Storage (Dev 3 làm)
class IStorage(Protocol):
    def save_chunk(self, chunk_hash: str, data: bytes) -> bool: ...
    def get_chunk(self, chunk_hash: str) -> bytes: ...
    def save_manifest(self, manifest: SnapshotManifest) -> bool: ...
    def load_manifest(self, snapshot_id: str) -> SnapshotManifest: ...
    def list_snapshots(self) -> List[str]: ...

# Giao diện cho Logic (Dev 2 làm)
class ILogic(Protocol):
    def chunk_data(self, file_path: str) -> List[str]: ... # Trả về list hash
    def create_manifest(self, label: str, root_path: str) -> SnapshotManifest: ...
    def verify_merkle(self, manifest: SnapshotManifest) -> bool: ...

# Giao diện cho Security (Dev 4 làm)
class ISecurity(Protocol):
    def get_current_user(self) -> str: ... 
    def check_permission(self, user: str, command: str) -> bool: ... 
    def log_audit(self, user: str, command: str, args: str, status: str): ... 
    def verify_audit_log(self) -> bool: ...